// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using MyApps.CustomerManagement.sdk;
using MyApps.CustomerManagement.sdk.Models;

namespace MyApps.CustomerManagement.sdk
{
    public static partial class ArticleOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static object Delete(this IArticleOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IArticleOperations)s).DeleteAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> DeleteAsync(this IArticleOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.DeleteWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        public static IList<Article> Get(this IArticleOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IArticleOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Article>> GetAsync(this IArticleOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<MyApps.CustomerManagement.sdk.Models.Article>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static Article GetById(this IArticleOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IArticleOperations)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Article> GetByIdAsync(this IArticleOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<MyApps.CustomerManagement.sdk.Models.Article> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object Post(this IArticleOperations operations, Article value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IArticleOperations)s).PostAsync(value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostAsync(this IArticleOperations operations, Article value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostWithOperationResponseAsync(value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object Put(this IArticleOperations operations, int id, Article value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IArticleOperations)s).PutAsync(id, value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IArticleOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PutAsync(this IArticleOperations operations, int id, Article value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PutWithOperationResponseAsync(id, value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
