// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using MyApps.CustomerManagement.sdk;
using MyApps.CustomerManagement.sdk.Models;

namespace MyApps.CustomerManagement.sdk
{
    public static partial class CustomerOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static object Delete(this ICustomerOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).DeleteAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> DeleteAsync(this ICustomerOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.DeleteWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        public static IList<Customer> Get(this ICustomerOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Customer>> GetAsync(this ICustomerOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<MyApps.CustomerManagement.sdk.Models.Customer>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static Customer GetById(this ICustomerOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Customer> GetByIdAsync(this ICustomerOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<MyApps.CustomerManagement.sdk.Models.Customer> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object Post(this ICustomerOperations operations, Customer value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).PostAsync(value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostAsync(this ICustomerOperations operations, Customer value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostWithOperationResponseAsync(value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object Put(this ICustomerOperations operations, int id, Customer value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).PutAsync(id, value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PutAsync(this ICustomerOperations operations, int id, Customer value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PutWithOperationResponseAsync(id, value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
