// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using MyApps.CustomerManagement.sdk;
using MyApps.CustomerManagement.sdk.Models;

namespace MyApps.CustomerManagement.sdk
{
    public static partial class OrderOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static object Delete(this IOrderOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOrderOperations)s).DeleteAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> DeleteAsync(this IOrderOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.DeleteWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        public static IList<Order> Get(this IOrderOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOrderOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Order>> GetAsync(this IOrderOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<MyApps.CustomerManagement.sdk.Models.Order>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static Order GetById(this IOrderOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOrderOperations)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Order> GetByIdAsync(this IOrderOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<MyApps.CustomerManagement.sdk.Models.Order> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object Post(this IOrderOperations operations, Order value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOrderOperations)s).PostAsync(value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostAsync(this IOrderOperations operations, Order value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostWithOperationResponseAsync(value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object Put(this IOrderOperations operations, int id, Order value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOrderOperations)s).PutAsync(id, value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyApps.CustomerManagement.sdk.IOrderOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PutAsync(this IOrderOperations operations, int id, Order value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PutWithOperationResponseAsync(id, value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
