// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using MyApps.CustomerManagement.sdk;

namespace MyApps.CustomerManagement.sdk
{
    public partial class TestWebApi : ServiceClient<TestWebApi>, ITestWebApi
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IArticleOperations _article;
        
        public virtual IArticleOperations Article
        {
            get { return this._article; }
        }
        
        private ICustomerOperations _customer;
        
        public virtual ICustomerOperations Customer
        {
            get { return this._customer; }
        }
        
        private IOrderOperations _order;
        
        public virtual IOrderOperations Order
        {
            get { return this._order; }
        }
        
        /// <summary>
        /// Initializes a new instance of the TestWebApi class.
        /// </summary>
        public TestWebApi()
            : base()
        {
            this._article = new ArticleOperations(this);
            this._customer = new CustomerOperations(this);
            this._order = new OrderOperations(this);
            this._baseUri = new Uri("http://localhost:50152");
        }
        
        /// <summary>
        /// Initializes a new instance of the TestWebApi class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public TestWebApi(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._article = new ArticleOperations(this);
            this._customer = new CustomerOperations(this);
            this._order = new OrderOperations(this);
            this._baseUri = new Uri("http://localhost:50152");
        }
        
        /// <summary>
        /// Initializes a new instance of the TestWebApi class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public TestWebApi(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._article = new ArticleOperations(this);
            this._customer = new CustomerOperations(this);
            this._order = new OrderOperations(this);
            this._baseUri = new Uri("http://localhost:50152");
        }
        
        /// <summary>
        /// Initializes a new instance of the TestWebApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public TestWebApi(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the TestWebApi class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public TestWebApi(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the TestWebApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public TestWebApi(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
