// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace CustomerManagement.sdk
{
    public static partial class TestWebApiExtensions
    {
    }
}
