// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace MyApps.CustomerManagement.sdk.Models
{
    public partial class Customer
    {
        private string _adresse;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Adresse
        {
            get { return this._adresse; }
            set { this._adresse = value; }
        }
        
        private int? _customerId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CustomerId
        {
            get { return this._customerId; }
            set { this._customerId = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _phone;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Phone
        {
            get { return this._phone; }
            set { this._phone = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Customer class.
        /// </summary>
        public Customer()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken adresseValue = inputObject["Adresse"];
                if (adresseValue != null && adresseValue.Type != JTokenType.Null)
                {
                    this.Adresse = ((string)adresseValue);
                }
                JToken customerIdValue = inputObject["CustomerId"];
                if (customerIdValue != null && customerIdValue.Type != JTokenType.Null)
                {
                    this.CustomerId = ((int)customerIdValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken phoneValue = inputObject["Phone"];
                if (phoneValue != null && phoneValue.Type != JTokenType.Null)
                {
                    this.Phone = ((string)phoneValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Customer
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Adresse != null)
            {
                outputObject["Adresse"] = this.Adresse;
            }
            if (this.CustomerId != null)
            {
                outputObject["CustomerId"] = this.CustomerId.Value;
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            if (this.Phone != null)
            {
                outputObject["Phone"] = this.Phone;
            }
            return outputObject;
        }
    }
}
