// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using CustomerManagement.sdk.Models;
using Newtonsoft.Json.Linq;

namespace CustomerManagement.sdk.Models
{
    public static partial class ArticleCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Article> DeserializeJson(JToken inputObject)
        {
            IList<Article> deserializedObject = new List<Article>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Article article = new Article();
                article.DeserializeJson(iListValue);
                deserializedObject.Add(article);
            }
            return deserializedObject;
        }
    }
}
